language: node_js
node_js:
- 13.11.0
branches:
  only:
    - master
    - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.14.2
- npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
env:
  global:
  - secure: YeV6Z77qCDUMz51FybwQ3yTxVY5oyin7RaZRomtjoyrKr4RK1M6M55UGyj2My7UdFQJbPMsGdPMouzi6G0+jmv/zgwu7KD7IxJ8RHij4aamyBTk/2JvrY7gtgSdrLTP4oOWm4uQY07DNPsvleuVXUJbXyFNHkjRaiG4KScj84Ss97BeTtMREHMR8IY6aaklRzxwFjtfhL3C6L/wIIrbpWuMGnO56JOPkOYDgU2hR5I3BCVCJTXt+cEUgFT0drwT/YhsE9exW0hXyVjCAuYu1Lgip/WJW8F4EEE8sGG/tI0dPTbMT7vzKN2gxTDTzYBk96fF3YF3/gIvUR0mbjHyK08KyqeOWL4DwtHX4ekOlSV6PU4gPV/znSiiVY9Vl1zIg66rpIOhSNxn/g0OZCAXu2WMt1xTl4ka/ReNBt2AqlDlcxjrYJT2xfnHjUJrKPVZCwySGl8S0GaUpijriKrvcjC+NAafqzBGMPcS2Vg8c/QqHcOG7DJrOFN1y6SYpKjfag9CVEKeL+jqj4fpR6afwi2r6gxPrm0283WHZOV1XzGUeumYHd3JhQqdp1fIMRMmGacQlyqJCJIfWEi7am0yOzP1qr8xm8Ffmxs0P9Ott7QHLgwErU6QWb0f7BvjidQPnrF4B6/fIAtlwuDHIgaYVGznePDkJlPSZlAOBQ0lE/t8=
  - secure: JXjOn4LlB4kLbf9Q+I6D7n6qw290twnJHkxOTYAltNUHjLScHMjKw80BEeyjw5UlE50KYxvMv8WieP9zIfjtYpBC8qHjAnOUkAtC8Yu+fk2UNOORXtrSlV6z9D4TwtYTYWNba3jxH9MgCR5J62To+NgYYEi7zef1CNNHk6sbQjFPh1DLwBZvvjNU73RaaQcFo5OaeCHbADbkQLJ/dryTlNmBNcdSk0yyZ5JAHSeY4wzSFjYFg+SlRXbqjH8In2ZLPj26gnb4cBX5V0bgS8sXNCBoVmgubVh8wq9jTitHWRXhzsSgA+ceEaOpmP3EArduiWhOQ8Alibuu004bPxGmp8cN1U70qHZcNvYYLn2bUfs2egf2940yfn9kAtHbMh/QoAjGtwfHLxdwPF+HC4dd7if0j9vdPwUtiajN62rrsk/W9icGdvQtOr/LLhCnDlk3BXnWY7N6tdPbQq3/B8I7n7EMImrKPWd5aYWa63CsocbFD8fdEDC3nJBaRcnjDEJ80c8iwry1bNY3c4ejJ3N3OLIGxFNW7CpREljZIiCAhhFJAbf+KEyATcqy3if6xVPWJr5fSP5ikgx6wEuOGjYD3dIoHc6k/6FTLOjZDXtxu3IubfvZBWtE4S3q8aNFSEnBklJH801GYCPB2HRyFSlYtTvwW0XHqSxrzdghzySNA/A=
  - secure: Hi1XjqoXHSrOwiHZp5BlAasBH+QoA8jcpDka6Egx9ri4dSoxcGI5lG0O3QE2h2Wil+8PdmJQekDGsWVKZZhKjmHXRCSVixJhLGgQUdsFCzQrcws30NhfhSkleLWSm1Bybe7mjEWqRqBysgphzbpy05lUQ86niUN9QhyHy1TIY4RVJyGUvLct8DUoMABfDTpYxjCJ5syEHXK1X6tRVqT7z/7iVqe2Nt4YcwkotLs5eXE+acjW/LJeIFvTItISLeRagvMXcuY9u0q7vCwHC8KxJ6Xy2R6k5G1oeVNsA+DlYunpqY5QECYW/FxADDAEBoraKE4jvgoGtXUyCN2tnDBeAe76ldsZZAdTkQIWhTPSOOuE7+CprWwvpcpDEpRTbth5d13UjMdNPYcU+ZZRp99zSdbAWFndTkqQNKC5/0lHs4jW/Um4/wt+Xg2uFnDa/Etk976qsgI5FbD3Np97geW118aE9+nZ2zEVmNw80Hw6D5z2qnPbdf2C1lJgG8CAC3PaFgbG28eKVNAtu7lgsaDIYuhCq6xkoG6yTkFIG6zyUBO1S2TTuoZGSuKQPuX39elDTvwZ9VNMYp6RJdc6tCVqYfuphoLggSvtWtqBEGdnQZxoNMdEbXRWUc3iPwn2931B1tVOXhAs0jcBDteEnvpT6Ny1OfiLmkP+6UnrGG3TpmY=
jobs:
  include:
  - stage: Tests
    name: Integration Tests
    script: npm run test-integration
  - stage: Tests
    name: Unit Tests
    script: npm run test-unit
  - stage: Tests
    name: eslint
    script: npm run eslint
  - stage: publish
    if: tag IS present
    script: npm publish
  - stage: Deploy Staging
    if: NOT type IN (pull_request)
    script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - mkdir $TRAVIS_BUILD_DIR/upload
    - cp -r src build
    - cp -r bin build
    - cp package.json build
    - cp package-lock.json build
    - mv .codedeploy-stg/appspec.yml build/appspec.yml
    - mv .codedeploy-stg/ build/.codedeploy
    - cd build; tar -czvf $TRAVIS_BUILD_DIR/upload/tracker-${TRAVIS_JOB_ID}.tar .;tar
      -czvf $TRAVIS_BUILD_DIR/upload/latest.tar .;
    - cd $TRAVIS_BUILD_DIR;
    deploy:
    - provider: s3
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: iGtMZxN+fvrqkMM5VP86eb8GrYXtx7fas7nLKcGsZde1iikO85vLeP8dR/yIARnZ8I044EDxhETbIDUsw0Y3+uW/num9a2xehoKIV19YEr7B+yyxp0wJNEfmBR6EYOq77XR+7BGLNyxdkFVHSfU51WsmU3JjVd4kCxvgSbjraj9/NVp/EJ/4+WqbTiWaOinJSiqtyVxnRkJ4ofqz+ZG5UzFXChAIhDC0rgN5ZhCz1uBl1ofuJ+8ULQODSj4v0zeU4OFkhOCIyk92ujRFf9qZWHVwNN0fRs/qfusyN5jjf9kffebMGOhrzEG0KT6iyUp81gZX80k24+73G1KfeZKy7q2vrJ0gX+II8MOyjv77bU4ohPWpBlDsxicoSg1AiJcaPjq/42tQnA/Rcw+u60X91QTvufgHouTkkFK81/HLNkCuUbfQX5hghUyx+/Az3+4YvQ98ZPzjnMnPGcblI2iM9O5C+T05dsreBPGQMIcjVoIhlbNeNgk5VXq5OteqpAV1t9jMOfy/b6t5NtlCBBfJTFzTvGggIW4dsFAZ2Fbn4nZCyHhtinjZoysIwp9MyO9aOvcGCHuiTZh0OcEUxTtxMq6Hkk0Qwp4sw98Cj8f59fL6hrjU39s7FCWxozCDTxO9Q43JQ8gjzex+vC3Vl00UD54PTwWfnWynLsJwHzXqmSA=
      bucket: eu-west-1-stg-streamr-vault
      upload-dir: tracker-node/releases
      acl: private
      region: eu-west-1
      skip_cleanup: true
      local_dir: upload
    - provider: codedeploy
      access_key_id: AKIAI3FGPGMK3EREJJTQ
      secret_access_key:
        secure: iGtMZxN+fvrqkMM5VP86eb8GrYXtx7fas7nLKcGsZde1iikO85vLeP8dR/yIARnZ8I044EDxhETbIDUsw0Y3+uW/num9a2xehoKIV19YEr7B+yyxp0wJNEfmBR6EYOq77XR+7BGLNyxdkFVHSfU51WsmU3JjVd4kCxvgSbjraj9/NVp/EJ/4+WqbTiWaOinJSiqtyVxnRkJ4ofqz+ZG5UzFXChAIhDC0rgN5ZhCz1uBl1ofuJ+8ULQODSj4v0zeU4OFkhOCIyk92ujRFf9qZWHVwNN0fRs/qfusyN5jjf9kffebMGOhrzEG0KT6iyUp81gZX80k24+73G1KfeZKy7q2vrJ0gX+II8MOyjv77bU4ohPWpBlDsxicoSg1AiJcaPjq/42tQnA/Rcw+u60X91QTvufgHouTkkFK81/HLNkCuUbfQX5hghUyx+/Az3+4YvQ98ZPzjnMnPGcblI2iM9O5C+T05dsreBPGQMIcjVoIhlbNeNgk5VXq5OteqpAV1t9jMOfy/b6t5NtlCBBfJTFzTvGggIW4dsFAZ2Fbn4nZCyHhtinjZoysIwp9MyO9aOvcGCHuiTZh0OcEUxTtxMq6Hkk0Qwp4sw98Cj8f59fL6hrjU39s7FCWxozCDTxO9Q43JQ8gjzex+vC3Vl00UD54PTwWfnWynLsJwHzXqmSA=
      bucket: eu-west-1-stg-streamr-vault
      key: tracker-node/releases/tracker-${TRAVIS_JOB_ID}.tar
      application: eu-west-1-stg-tracker-node-codedeploy
      deployment_group: eu-west-1-stg-tracker-node-deployment-group
      region: eu-west-1
  - stage: Build s3 Lisboa
    if: NOT type IN (pull_request)
    script:
    - mkdir $TRAVIS_BUILD_DIR/build
    - mkdir $TRAVIS_BUILD_DIR/upload
    - PACKAGE_VERSION=${TRAVIS_TAG:1}
    - sed -i "s/PACKAGE_VERSION/$PACKAGE_VERSION/g" .codedeploy/after_install.sh
    - mv .codedeploy/appspec.yml build/appspec.yml
    - mv .codedeploy/ build/
    - cd build; tar -czvf $TRAVIS_BUILD_DIR/upload/tracker-${TRAVIS_TAG}.tar .;tar
      -czvf $TRAVIS_BUILD_DIR/upload/latest.tar .;
    - cd $TRAVIS_BUILD_DIR;
    deploy:
    - provider: s3
      access_key_id: AKIAJBAGP3WA5UXQ3AZQ
      secret_access_key:
        secure: hvpO6AWRLNy46T2HGS/Z8rIvyqGQ90CCyqmnhS71KujcsgNTbF/F1eHUIjQKHB8yN8WdZYtV2oG6pH5zi07F+rjoR4qh817O8AEcf4rgaWuONWhbpQUgxD0BTOgevPpEy+W2e4JbIANNUFC9z5yfgyZ1hbl6hfa5zxGMGMjUtRg2gsWbkXSybWsYWcQnAjtsUyNTlXasUC8u7o6Com/Ml/IZ/ffen/zurtKBdd5m6LIFj32flzXfT2yfxcNnC2N8jrTCGi7BMvPotH4zraRPpOFlIqPw13UHDfWDbApdNQ+q7axPbHiAXzPE6K0ovo4/c6L5MCkS91EdzTEvLc11m3DwnMKVYC5WFHjFkxO79cM9MoeLWKX4kpUe8sW2fC+QyniqopBewR1d7pONosm1HVGlGjd2dZOG/LwtmP69JTO9QB2/Y1OZMQBbaLwlOPHwm2WB1IWhO8n/IuIzks8u/9hswNbMfGLUxQcIfA+0dzgmFXBzHkA8xNfENQn/7AwmXD/61ER+e/Smyk/Cl32YVRNCqPZnZeMSKoTiXfPRjbLdxZdWSNOhfDjinyHI+4iHti6ao2IrkB4A+M76+Nt7exdT9JG2kDmQfWNatcvlv3SWDUBJkcaUgMJljUgze/XtXoBF5uoutSwQihRU/54yx7F6lUy2EVW/Z3uni7CeiBA=
      bucket: eu-west-1-lx-streamr-vault
      upload-dir: tracker-node/releases
      acl: private
      region: eu-west-1
      skip_cleanup: true
      local_dir: upload
      on:
        tags: true
