language: node_js
node_js:
- '8.12.0'
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.4.1
jobs:
  include:
  - stage: tests
    name: lint
    script: npm run eslint
  - script: npm run test-unit
    name: unit tests
  - script: npm run test-integration
    name: integration tests
