language: node_js
node_js:
- '8.12.0'
sudo: true
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.4.1
jobs:
  include:
  - stage: tests
    script:
      - npm run eslint
      - npm run test-unit
      - npm run test-integration
