language: node_js
node_js:
- '8.12.0'
sudo: true
services:
  - cassandra
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
- npm i -g npm@6.4.1
before_script: |-
  cqlsh -e "CREATE KEYSPACE IF NOT EXISTS streamr_dev WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };"
jobs:
  include:
  - stage: tests
    name: lint
    script: npm run eslint
  - name: unit tests
    script: npm run test-unit
  - name: integration tests
    script: npm run test-integration
