name: Generate Docs

on:
  push:
    branches:
      - master # Set a branch name to trigger deployment

jobs:
  build:
    name: Run build using Node 14.x
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: npm ci
        run: npm ci
      - name: npm run docs
        run: npm run docs
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

